---
title: "range2"
---
<br>
```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "> "
)
```

```{r setup}
library(cuteTool)
```
<br>

### Datasets

```{r}
vec1 <- -1:3 # vector of integers
vec2 <- c(1:3, NA) # vector of integers with NA
vec3 <- c(1:3, Inf) # vector of integers with Inf
vec4 <- 1:3 / 3 # vector of proportions
vec5 <- c(1, 2, NA, -Inf) # vector of integers but stored as "double", with NA and Inf
log1 <- c(TRUE, FALSE, NA) # logical vector with NA
log2 <- c(TRUE, FALSE, FALSE) # logical vector                    
cpx <- as.complex(vec1) # complex vector
mat1 <- matrix(vec1) # 1D matrix of integers
mat2 <- matrix(vec5) # 1D matrix of integers, NA and Inf
mat3 <- matrix(log1) # 1D matrix of logical values
mat4 <- matrix(log2) # 1D matrix of logical values and NA
fac1 <- factor(vec5) # 1D factor
tab1 <- table(fac1) # 1D table
```

<br>

### Datasets info

```{r}
vec1 # vector of integers
vec2 # vector of integers with NA
vec3 # vector of integers with Inf
vec4 # vector of proportions
vec5 # vector of integers but stored as "double", with NA and Inf
log1 # logical vector with NA
log2 # logical vector                    
cpx # complex vector
mat1 # 1D matrix of integers
mat2 # 1D matrix of integers, NA and Inf
mat3 # 1D matrix of logical values
mat4 # 1D matrix of logical values and NA
fac1 # 1D factor
tab1 # 1D table
```
<br>

### Simple examples

```{r}
range2(x = vec1) # vector of integers
range2(x = vec2) # vector of proportions
range2(x = vec3) # vector of integers but stored as "double", with NA and Inf
range2(x = vec4) # vector of proportions
range2(x = vec5) # vector of integers but stored as "double", with NA and Inf
range2(x = log1) # vector of characters
range2(x = log2) # vector of characters with NA
range2(x = cpx) # complex vector
range2(x = mat1) # 1D matrix of integers
range2(x = mat2) # 1D matrix of integers, NA and Inf
range2(x = mat3) # 1D matrix of logical values
range2(x = mat4) # 1D matrix of logical values and NA
range2(x = fac1) # 1D factor
range2(x = tab1) # 1D table
```
<br>

### Argument na.rm
```{r}
range2(
    x = vec1, 
    na.rm = TRUE
)

range2(
    x = vec2, 
    na.rm = TRUE
)

range2(
    x = log2, 
    na.rm = TRUE
)

range2(
    x = log1, 
    na.rm = TRUE
)

range2(
    x = mat3, 
    na.rm = TRUE
)
```

### Argument finite
```{r}
range2(
    x = vec1,
    finite = TRUE
)

range2(
    x = vec3,
    finite = TRUE
)
```

### All the arguments
```{r}
range2(
    x = vec5,
    na.rm = TRUE,
    finite  = FALSE
)

range2(
    x = cpx,
    na.rm = TRUE,
    finite  = FALSE
)
```